"""Phase-separated generation — system-controlled perception traces.

The core problem: if an LLM self-reports its perception trace, it can
fabricate the order in which it "noticed" clues.  The trace must be
generated by the *system*, not claimed by the model.

This module provides ``PhasePromptGenerator`` which:

    1. Feeds the LLM one phase at a time (micro-capture → observations →
       anomalies → hypotheses → contradictions → elimination)
    2. Records what the LLM produces at each phase with system timestamps
    3. Builds a ``PerceptionTrace`` that the reward engine can trust

The generator is LLM-agnostic — it produces prompt strings and consumes
response strings.  The caller handles the actual LLM API calls.

Usage (training loop pseudocode):

    from detective_engine.engine.phase_generator import PhasePromptGenerator
    from detective_engine.engine.reward_interface import RewardScorer

    scorer = RewardScorer()
    case_prompt = scorer.case_prompt("C001")

    gen = PhasePromptGenerator(case_prompt)

    # Phase 0: micro-capture
    prompt_0 = gen.phase_prompt(0)
    response_0 = llm.generate(prompt_0)
    gen.record_response(0, response_0)

    # Phase 1-6: remaining phases
    for phase in range(1, 7):
        prompt_n = gen.phase_prompt(phase)
        response_n = llm.generate(prompt_n)
        gen.record_response(phase, response_n)

    # Get system-controlled outputs
    analysis = gen.build_analysis()       # structured dict for score()
    trace = gen.build_trace(evidence_map) # system-generated PerceptionTrace
    result = scorer.score("C001", analysis, perception_trace=trace)
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from typing import Any

from .models import (
    EvidenceMeta,
    ObservationEvent,
    PerceptionConfig,
    PerceptionTrace,
    normalize_key,
)
from .perception_integrity import match_evidence_ids


# ---------------------------------------------------------------------------
# Phase definitions
# ---------------------------------------------------------------------------

PHASE_NAMES = {
    0: "micro_capture",
    1: "observations",
    2: "anomalies",
    3: "hypotheses",
    4: "contradictions",
    5: "false_narrative",
    6: "elimination",
}


@dataclass
class PhaseRecord:
    """System-recorded output for a single generation phase."""
    phase: int
    name: str
    prompt: str
    response: str = ""
    timestamp_start: float = 0.0   # when prompt was sent
    timestamp_end: float = 0.0     # when response was received
    items: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Prompt templates
# ---------------------------------------------------------------------------

_PHASE_PROMPTS = {
    0: (
        "You are analyzing a detective case. Here is the evidence:\n\n{evidence}\n\n"
        "PHASE 0 — MICRO-CAPTURE\n"
        "List the first 3 raw details you notice. Be brief — no explanations.\n"
        "Format: one detail per line, prefixed with a dash."
    ),
    1: (
        "Good. Now proceed to detailed observation.\n\n"
        "PHASE 1 — RAW OBSERVATIONS\n"
        "List ONLY what you see in the evidence. No interpretations. No assumptions.\n"
        "List at least 5 observations, one per line, prefixed with a dash."
    ),
    2: (
        "Now look for tensions.\n\n"
        "PHASE 2 — ANOMALIES & TENSIONS\n"
        "What tensions or oddities exist between the facts?\n"
        "List at least 2, one per line, prefixed with a dash."
    ),
    3: (
        "Now generate competing explanations.\n\n"
        "PHASE 3 — MULTIPLE EXPLANATIONS\n"
        "For each of the first 3 observations you listed in Phase 1, "
        "provide 2-3 possible explanations.\n"
        "Format:\n"
        "\"observation text\":\n"
        "- explanation 1\n"
        "- explanation 2\n"
    ),
    4: (
        "Now detect contradictions.\n\n"
        "PHASE 4 — CONTRADICTION DETECTION\n"
        "Identify pairs of facts that cannot coexist under the surface story.\n"
        "{contradiction_hint}\n"
        "Format: one contradiction per line, prefixed with a dash."
    ),
    5: (
        "Now reject the false narrative.\n\n"
        "PHASE 5 — FALSE NARRATIVE REJECTION\n"
        "{false_narrative_hint}\n"
        "State the most obvious but WRONG explanation this scene sells, "
        "and explain why it fails."
    ),
    6: (
        "Final phase.\n\n"
        "PHASE 6 — ELIMINATION & REASONING CHAIN\n"
        "{scenarios}\n"
        "Which scenario do you ELIMINATE? State it clearly.\n"
        "Then provide your reasoning chain — at least 3 reasons, one per line."
    ),
}


# ---------------------------------------------------------------------------
# PhasePromptGenerator
# ---------------------------------------------------------------------------

class PhasePromptGenerator:
    """Generates phase-separated prompts and records LLM responses.

    System-controlled: the generator decides what the LLM sees at each step,
    and records timestamps that the LLM cannot fabricate.
    """

    def __init__(self, case_prompt: dict[str, Any]):
        """Initialize with a case prompt from ``RewardScorer.case_prompt()``."""
        self._case = case_prompt
        self._evidence_text = "\n".join(
            f"  {i+1}. {e}" for i, e in enumerate(case_prompt["evidence"])
        )
        self._records: dict[int, PhaseRecord] = {}

    def phase_prompt(self, phase: int) -> str:
        """Generate the prompt for a given phase.

        Call this BEFORE sending to the LLM.  Records the start timestamp.
        """
        if phase not in PHASE_NAMES:
            raise ValueError(f"Unknown phase: {phase}. Valid: {list(PHASE_NAMES)}")

        template = _PHASE_PROMPTS[phase]

        # Build substitution context
        ctx: dict[str, str] = {
            "evidence": self._evidence_text,
            "contradiction_hint": "",
            "false_narrative_hint": "",
            "scenarios": "",
        }

        if self._case.get("has_contradictions"):
            n = 1  # we don't reveal count — just hint
            ctx["contradiction_hint"] = "There are hidden contradictions in this scene."

        if self._case.get("must_reject_false_narrative"):
            ctx["false_narrative_hint"] = (
                "This scene contains a false narrative designed to mislead."
            )
        else:
            ctx["false_narrative_hint"] = (
                "If you see an obvious but wrong explanation, state and reject it. "
                "Otherwise, skip this phase."
            )

        if self._case.get("scenarios"):
            ctx["scenarios"] = "Candidate scenarios:\n" + "\n".join(
                f"  - {s}" for s in self._case["scenarios"]
            )

        prompt = template.format(**ctx)

        # For phases 1+, prepend context from previous phases
        if phase > 0:
            context_lines = []
            for prev_phase in range(phase):
                if prev_phase in self._records and self._records[prev_phase].response:
                    rec = self._records[prev_phase]
                    context_lines.append(
                        f"--- Your Phase {prev_phase} ({rec.name}) response ---\n"
                        f"{rec.response}\n"
                    )
            if context_lines:
                prompt = "\n".join(context_lines) + "\n" + prompt

        # Record start
        self._records[phase] = PhaseRecord(
            phase=phase,
            name=PHASE_NAMES[phase],
            prompt=prompt,
            timestamp_start=time.time(),
        )

        return prompt

    def record_response(self, phase: int, response: str) -> None:
        """Record the LLM's response for a phase.  Sets system timestamp."""
        if phase not in self._records:
            raise ValueError(f"Phase {phase} prompt not yet generated")
        rec = self._records[phase]
        rec.response = response.strip()
        rec.timestamp_end = time.time()
        rec.items = self._parse_items(response)

    def _parse_items(self, text: str) -> list[str]:
        """Extract list items from a response."""
        items = []
        for line in text.strip().split("\n"):
            line = line.strip()
            m = re.match(r"^\s*[-*•]\s+(.+)|^\s*\d+[\.\)]\s+(.+)", line)
            if m:
                item = (m.group(1) or m.group(2)).strip()
                if item:
                    items.append(item)
            elif line and len(line.split()) >= 3 and not line.startswith("#"):
                items.append(line)
        return items

    def _parse_hypotheses(self) -> dict[str, list[str]]:
        """Parse Phase 3 response into {observation: [explanations]}."""
        if 3 not in self._records:
            return {}

        text = self._records[3].response
        hypotheses: dict[str, list[str]] = {}
        current_key: str | None = None
        current_exps: list[str] = []

        for line in text.split("\n"):
            line = line.strip()
            if not line:
                continue

            # Key line: "observation text": or **observation**:
            key_match = re.match(
                r'^["\'](.+?)["\']\s*:|^\*\*(.+?)\*\*\s*:', line
            )
            if key_match:
                if current_key and current_exps:
                    hypotheses[current_key] = current_exps
                current_key = (key_match.group(1) or key_match.group(2)).strip()
                current_exps = []
                continue

            # Explanation under current key
            item_match = re.match(r"^\s*[-*•]\s+(.+)|^\s*\d+[\.\)]\s+(.+)", line)
            if item_match and current_key:
                exp = (item_match.group(1) or item_match.group(2)).strip()
                if exp:
                    current_exps.append(exp)

        if current_key and current_exps:
            hypotheses[current_key] = current_exps

        # Fallback
        if not hypotheses and 3 in self._records:
            items = self._records[3].items
            if items:
                obs_key = "general"
                if 1 in self._records and self._records[1].items:
                    obs_key = self._records[1].items[0]
                hypotheses[obs_key] = items

        return hypotheses

    # ------------------------------------------------------------------
    # Build outputs
    # ------------------------------------------------------------------

    def build_analysis(self) -> dict[str, Any]:
        """Build the analysis dict from recorded phases.

        This is the dict you pass to ``RewardScorer.score()``.
        """
        # Phase 6: split into elimination target + reasons
        elim_target = ""
        reasons = []
        if 6 in self._records:
            items = self._records[6].items
            if items:
                elim_target = items[0]
                reasons = items[1:] if len(items) > 1 else items

        return {
            "observations": self._records[1].items if 1 in self._records else [],
            "anomalies": self._records[2].items if 2 in self._records else [],
            "hypotheses": self._parse_hypotheses(),
            "elimination_target": elim_target,
            "reasons": reasons,
            "false_narrative_rejection": (
                self._records[5].response if 5 in self._records else ""
            ),
            "contradiction_notes": (
                self._records[4].items if 4 in self._records else []
            ),
        }

    def build_trace(
        self,
        evidence_map: dict[str, EvidenceMeta] | None = None,
        config: PerceptionConfig | None = None,
    ) -> dict[str, Any]:
        """Build a system-controlled perception trace dict.

        Timestamps come from the system (``time.time()`` at record time),
        NOT from the LLM.  This is the key anti-fabrication property.

        Returns a dict suitable for ``RewardScorer.score(perception_trace=...)``.
        """
        evidence_map = evidence_map or {}
        cfg = config or PerceptionConfig()

        # Phase 0 → initial (micro-capture)
        initial: list[dict[str, Any]] = []
        if 0 in self._records:
            rec = self._records[0]
            for idx, item in enumerate(rec.items):
                initial.append({
                    "text": item,
                    "timestamp": rec.timestamp_start + idx * 0.01,
                    "phase": "initial",
                    "order_index": idx,
                })

        # Phase 1 → later observations
        later: list[dict[str, Any]] = []
        if 1 in self._records:
            rec = self._records[1]
            for idx, item in enumerate(rec.items):
                later.append({
                    "text": item,
                    "timestamp": rec.timestamp_start + idx * 0.01,
                    "phase": "later",
                    "order_index": idx,
                })

        return {
            "initial": initial,
            "later": later,
            "_system_generated": True,
            "_phase_timestamps": {
                phase: {
                    "start": rec.timestamp_start,
                    "end": rec.timestamp_end,
                }
                for phase, rec in self._records.items()
            },
        }

    def get_phase_record(self, phase: int) -> PhaseRecord | None:
        """Access a raw phase record for debugging."""
        return self._records.get(phase)

    @property
    def completed_phases(self) -> list[int]:
        """Phases that have recorded responses."""
        return sorted(
            p for p, r in self._records.items() if r.response
        )
